language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

script:
  - phpunit
  - phpcs --standard=PSR2 --encoding=UTF-8 -p src/ test/